server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://123.207.114.103:3306/gxqwebDB
    username: root
    password: lbw
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  http:
    multipart:
      max-file-size: 5MB
#server:
#  port: 8888
#  context-path: /NYGXQSystem

#spring:
#  datasource:
#    url: jdbc:mysql://123.206.69.177:3306/NYGXQSystemDemo
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: kingcos
#    password: 9512
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#  http:
#    multipart:
#      max-file-size: 5MB
